import React, { createContext, useState } from 'react'

const courses = [
  {
    id: 1,
    title: "C Programming",
    image: "/assets/c-program.jpg",
    description: "Learn the fundamentals of programming with C language.",
    about:
      "C is the mother of all programming languages. In this course, you’ll learn the fundamentals of computer programming using C, including how memory works, how data is stored, and how to implement algorithms efficiently. With hands-on practice, you’ll master variables, loops, arrays, functions, and pointers. By the end, you’ll have a strong base to move into advanced programming languages.",
    whatYouWillLearn: [
      "Understand the structure of C programs",
      "Work with variables, data types, and operators",
      "Control flow using loops and conditionals",
      "Master pointers and memory allocation",
      "Implement functions and modular programming",
    ],
    syllabus: [
      "Introduction to C and setting up environment",
      "Data types, variables, and constants",
      "Operators and expressions",
      "Conditional statements and loops",
      "Functions and recursion",
      "Arrays and strings",
      "Pointers and memory management",
      "File handling in C",
    ],
    requirements: [
      "Basic understanding of computers",
      "No prior coding experience required",
      "Interest in learning programming fundamentals",
    ],
    category: "Programming",
    rating: 4.6,
    projects: 2,
    level: "Beginner",
  },
  {
    id: 2,
    title: "C++ Programming",
    image: "/assets/cpp-pro.jpg",
    description: "Learn Object-Oriented Programming and advanced coding techniques in C++.",
    about:
      "C++ builds on C and introduces Object-Oriented Programming (OOP), which is the backbone of modern software development. This course covers everything from syntax and functions to advanced concepts like polymorphism, inheritance, and templates. With practical projects, you’ll be ready to solve real-world problems and gain a deep understanding of C++’s powerful features.",
    whatYouWillLearn: [
      "Understand OOP principles",
      "Work with classes and objects",
      "Use inheritance and polymorphism",
      "Handle templates and STL",
      "Implement advanced problem solving",
    ],
    syllabus: [
      "Basics of C++ and syntax",
      "Functions and arrays",
      "Object-oriented programming",
      "Constructors and destructors",
      "Inheritance and polymorphism",
      "Operator overloading",
      "Exception handling",
      "Standard Template Library (STL)",
    ],
    requirements: [
      "Basic knowledge of C programming",
      "Logical thinking skills",
      "Beginner-friendly approach to OOP",
    ],
    category: "Programming",
    rating: 4.7,
    projects: 3,
    level: "Intermediate",
  },
  {
    id: 3,
    title: "PHP Programming",
    image: "/assets/php-pro.jpg",
    description: "Create dynamic and interactive websites using PHP.",
    about:
      "PHP is one of the most widely used server-side scripting languages for web development. This course will take you from the basics of PHP syntax and variables to building fully functional web applications connected with MySQL databases. You’ll learn to manage sessions, handle forms, and build secure backend systems, making you job-ready for entry-level web development.",
    whatYouWillLearn: [
      "Understand PHP syntax and variables",
      "Work with forms and user input",
      "Handle sessions and cookies",
      "Integrate PHP with MySQL",
      "Build dynamic web applications",
    ],
    syllabus: [
      "Introduction to PHP",
      "Variables, operators, and data types",
      "Conditional statements and loops",
      "Functions and arrays",
      "Form handling in PHP",
      "Working with sessions and cookies",
      "Database integration with MySQL",
      "Building a mini project",
    ],
    requirements: [
      "Basic knowledge of HTML & CSS",
      "Beginner-friendly for backend developers",
      "Willingness to learn dynamic web development",
    ],
    category: "Web Development",
    rating: 4.5,
    projects: 2,
    level: "Beginner",
  },
  {
    id: 4,
    title: "Laravel Framework",
    image: "/assets/laravel-p.jpg",
    description: "Build scalable web applications using Laravel and MVC architecture.",
    about:
      "Laravel is the most popular PHP framework, known for its elegance and simplicity. This course will guide you through Laravel’s MVC architecture, Blade templates, routing, and middleware. You’ll learn to work with Eloquent ORM for database handling, authentication, and API development. By the end, you’ll be able to create professional, scalable, and secure web applications with Laravel.",
    whatYouWillLearn: [
      "Understand Laravel MVC structure",
      "Work with routes and controllers",
      "Use Blade templating engine",
      "Handle databases with Eloquent ORM",
      "Build complete Laravel applications",
    ],
    syllabus: [
      "Introduction to Laravel framework",
      "Routing and controllers",
      "Blade templates and layouts",
      "Eloquent ORM and migrations",
      "Authentication and middleware",
      "RESTful APIs in Laravel",
      "File uploads and validation",
      "Project with Laravel",
    ],
    requirements: [
      "Knowledge of PHP",
      "Basic understanding of MySQL",
      "Suitable for beginners in frameworks",
    ],
    category: "Web Development",
    rating: 4.8,
    projects: 4,
    level: "Intermediate",
  },
  {
    id: 5,
    title: "CodeIgniter Framework",
    image: "/assets/codel.jpg",
    description: "Develop lightweight and fast applications with CodeIgniter.",
    about:
      "CodeIgniter is a simple and lightweight PHP framework for rapid application development. This course introduces you to its MVC structure, helping you learn how to create secure, scalable, and fast applications with minimal configuration. You’ll build projects from scratch and gain real experience implementing CRUD functionality and session management in CodeIgniter.",
    whatYouWillLearn: [
      "Understand CodeIgniter structure",
      "Work with controllers and views",
      "Use models for database handling",
      "Build applications with MVC pattern",
      "Implement CRUD functionality",
    ],
    syllabus: [
      "Introduction to CodeIgniter",
      "Configuration and setup",
      "Controllers and views",
      "Models and database integration",
      "Form validation",
      "Sessions and authentication",
      "CRUD operations",
      "Mini project using CodeIgniter",
    ],
    requirements: [
      "Basic knowledge of PHP and MySQL",
      "Beginner-friendly for frameworks",
      "Willingness to build projects",
    ],
    category: "Web Development",
    rating: 4.4,
    projects: 2,
    level: "Beginner",
  },
  {
    id: 6,
    title: "MySQL Database",
    image: "/assets/mysq.jpg",
    description: "Master relational databases and SQL with MySQL.",
    about:
      "Databases are at the heart of almost every modern application, and MySQL is one of the most popular relational databases in the world. This beginner-friendly course will help you understand database design, write powerful SQL queries, and optimize your databases for performance. You’ll gain hands-on experience with joins, indexes, stored procedures, and triggers.",
    whatYouWillLearn: [
      "Understand relational database concepts",
      "Create and manage databases",
      "Write SQL queries and joins",
      "Use constraints and indexes",
      "Optimize database performance",
    ],
    syllabus: [
      "Introduction to Databases",
      "Installing and configuring MySQL",
      "Database design and normalization",
      "SQL queries: SELECT, INSERT, UPDATE, DELETE",
      "Joins and relationships",
      "Indexes and constraints",
      "Stored procedures and triggers",
      "Database optimization",
    ],
    requirements: [
      "No prior database knowledge required",
      "Beginner-friendly for backend developers",
      "Interest in working with data",
    ],
    category: "Database",
    rating: 4.7,
    projects: 3,
    level: "Beginner",
  },
    {
    id: 7,
    title: "Backend Developer",
    image: "/assets/backend.png",
    description: "Master backend development with PHP, MySQL, and REST APIs.",
    about:
      "Backend development is the backbone of any web application. In this course, you’ll learn server-side programming using PHP and MySQL, along with RESTful API development. The focus is on real-world skills like integrating databases, creating secure endpoints, and mastering frameworks such as Laravel. By the end, you’ll be able to design scalable and secure backend systems.",
    whatYouWillLearn: [
      "C Fundamentals for strong programming basics",
      "Advanced C++ concepts for problem solving",
      "Integrating PHP with MySQL databases",
      "Building applications with Laravel framework",
      "Developing secure and scalable RESTful APIs",
    ],
    syllabus: [
      "C Fundamentals",
      "Advanced C++ Programming",
      "Introduction to PHP",
      "Database design with MySQL",
      "Building dynamic web apps with PHP & MySQL",
      "Laravel basics and advanced features",
      "Authentication and authorization",
      "RESTful API design and implementation",
    ],
    requirements: [
      "Basic knowledge of computers",
      "Understanding of logic and problem-solving",
      "No prior backend experience required",
    ],
    category: "Backend Development",
    rating: 4.7,
    projects: 3,
    level: "Intermediate",
  },
  {
    id: 8,
    title: "Full Stack Developer",
    image: "/assets/fullstack.png",
    description:
      "Learn frontend and backend technologies to build complete web applications.",
    about:
      "Full stack development gives you the power to build both the frontend and backend of applications. In this course, you’ll cover HTML, CSS, JavaScript for frontend, and PHP, MySQL, and frameworks like Laravel/CodeIgniter for backend. By the end, you’ll be confident in building and deploying full-fledged web applications.",
    whatYouWillLearn: [
      "Build responsive websites with HTML5 and CSS3",
      "Use JavaScript to add interactivity",
      "Develop backend logic with PHP",
      "Use Laravel/CodeIgniter frameworks",
      "Design and manage MySQL databases",
    ],
    syllabus: [
      "Introduction to HTML5 & CSS3",
      "JavaScript fundamentals",
      "Responsive web design",
      "PHP programming basics",
      "Working with MySQL databases",
      "Laravel/CodeIgniter framework essentials",
      "Building full-stack applications",
      "Deployment on live servers",
    ],
    requirements: [
      "Basic understanding of internet and web browsers",
      "No prior coding knowledge required",
      "Willingness to learn both frontend and backend",
    ],
    category: "Full Stack Development",
    rating: 4.8,
    projects: 4,
    level: "Beginner to Advanced",
  },
  {
    id: 9,
    title: "System Programmer",
    image: "/assets/system-program.png",
    description:
      "Dive deep into system programming with C and C++ to understand how computers work under the hood.",
    about:
      "System programming focuses on building software that interacts directly with the operating system and hardware. This course takes you into advanced C and C++ programming, algorithm design, memory management, and system architecture. By the end, you’ll have the skills to write efficient, low-level programs that power complex systems.",
    whatYouWillLearn: [
      "Deep dive into C programming",
      "Work with C++ data structures",
      "Design efficient algorithms",
      "Understand memory management",
      "Grasp system-level architecture",
    ],
    syllabus: [
      "C deep dive – pointers, memory, and performance",
      "C++ data structures and STL",
      "Algorithm design and analysis",
      "Dynamic memory management",
      "System calls and low-level programming",
      "Multithreading basics",
      "Understanding compilers and linkers",
      "System architecture overview",
    ],
    requirements: [
      "Strong interest in low-level programming",
      "Basic programming knowledge (C preferred)",
      "Curiosity to understand how computers work internally",
    ],
    category: "System Programming",
    rating: 4.6,
    projects: 2,
    level: "Advanced",
  },
];



export const CoursesContext = createContext();

export const CourseProvider = ({children})=>{
    const [Courses, setCourses] = useState(courses);

    return <CoursesContext.Provider value={{Courses}}>
        {children}
    </CoursesContext.Provider>
}